version: '2.1'
services:
  referral-payment-node:
    container_name: referral-payment-node
    restart: always
    depends_on:
      referral-payment-mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
      - $GLS_METRICS_HOST:$GLS_METRICS_PORT:$GLS_METRICS_PORT
    env_file:
      - .env

  referral-payment-mongo:
    container_name: referral-payment-mongo
    image: mongo:4
    restart: always
    healthcheck:
      test: mongo --eval 'db.getCollectionNames()'
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - referral_payment_mongodb_vol:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - services-tier

networks:
  services-tier:

volumes:
  referral_payment_mongodb_vol:
